#
# 该文件包含自定义网站所需的配置参数
#

# 网站名称（展示在页面头部）
name: LiuLiuLiuPi

# 简短简介/描述（展示在页面头部）
description: 个人博客

# 头像/个人图片地址（可使用你的 GitHub 头像链接）
avatar: https://avatars.githubusercontent.com/u/110837470?v=4&size=64

#
# 下方参数均为可选配置
#

# 在页脚展示你填写账号对应的社交图标，留空则不显示
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: barryclark/jekyll-now
  instagram:
  linkedin:
  pinterest:
  rss: # 随便填写任意内容即可启用 RSS 订阅图标
  twitter: 
  stackoverflow: # StackOverflow 个人主页地址，示例："users/50476/bart-kiers"
  youtube: # 格式 channel/<频道ID> 或 user/<用户名>
  googleplus: # 填写谷歌个人主页地址中 plus.google.com/ 后面的内容


# 填入你的 Disqus 站点短名称（不是账号用户名），开启文章评论功能
# 可在 Disqus 账号的设置页面找到短名称
disqus:

# 填入谷歌统计跟踪代码（格式示例：UA-2110908-2），开启访问统计
google_analytics:

# 你的网站完整访问地址（示例：http://barryclark.github.io 或 http://www.barryclark.co）
# 用于生成站点地图 Sitemap.xml 和 RSS 订阅源
url:

# 如果你使用 GitHub Pages 的项目仓库部署网站
# 访问地址格式为 http://你的用户名.github.io/仓库名
# 而非个人主页仓库 http://你的用户名.github.io
# 则需要在此填写仓库名作为根路径，示例："/repository-name"
baseurl: ""

#
# !! 下方配置参数无需修改 !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
